# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='dataEHoraDeInicio',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='dataEHoraDeInicio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='eventoPrincipal',
            field=models.CharField(max_length=200, null=True, verbose_name='eventoPrincipal'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='logotipo',
            field=models.CharField(max_length=200, null=True, verbose_name='logotipo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='palavrasChave',
            field=models.CharField(max_length=200, null=True, verbose_name='palavrasChave'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sigla',
            field=models.CharField(max_length=20, null=True, verbose_name='sigla'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='uf',
            field=models.CharField(max_length=2, null=True, verbose_name='uf'),
        ),
    ]
