# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20170508_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa'),
        ),
    ]
